language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

sudo: false

before_install:
    - composer config -g github-oauth.github.com "$GITHUB_TOKEN"

install:
    - composer global require "fxp/composer-asset-plugin:^1.2.0"
    - composer global require "codeception/codeception:*"
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - composer update

script:
    - codecept run
